Updated considerations and limitations
MicrosoftDocs/fabric-docs pull request #11
Opened 2023-05-25 13:14 UTC by saurabhr14

Updated considerations and limitations for Sovereign Clouds

2023-05-28 09:18 UTC, KesemSharabi requested changes

2023-05-28 09:18 UTC, KesemSharabi commented on docs/admin/feature-usage-adoption.md
> +* Audit log retention period for the Feature Usage and Adoption dataset/report is currently rolling 30 days only.
Please change to:

The report retains information for 30 days.

2023-05-28 09:18 UTC, KesemSharabi commented on docs/admin/monitoring-workspace.md
> +* Sovereign Clouds (GCC) are not yet supported in the initial public preview release.
Is this for all sovereign clouds or only CGS? I assume it's for all clouds so please change to this:

Sovereign clouds are not supported.

2023-05-29 07:09 UTC, KesemSharabi commented
#sign-off

2023-05-29 07:44 UTC, saurabhr14 commented
#sign-off

2023-05-29 10:46 UTC, chi-qin commented
#sign-off

2023-05-29 11:28 UTC, chi-qin commented
#sign-off

2023-05-29 11:30 UTC, chi-qin commented
#sign-off

2023-05-29 11:46 UTC, KesemSharabi commented
@chi-qin - there's a bug that's not letting us sign off.

2023-05-29 13:53 UTC, chi-qin commented
@KesemSharabi Yeah, I am the incident owner, I just use this for testing. Sry for some noise

2023-05-29 14:02 UTC, KesemSharabi commented
@chi-qin, no worries and thanks for trying to fix this!

2023-05-30 14:52 UTC, merged